### PR TITLE
Added Chinese translation

### PR DESCRIPTION
**Pull request by forpleuvoir**
Added Chinese translation, Perhaps the translation was not professional enough
Fixed an error in the English language (when looking at the configuration file again, I found that I am not sure)

### CODE REVIEW

**Comment by OKHI233** [comment]
I think labPBR and oldPBR shouldn't be translated, as it might be confusing to users who were looking for a PBR resource pack.

**Comment by tsumi7** [comment]
@OKHI233 could you suggest these changes inline? Alternatively make a PR based on this one with your changes applied.

**Comment by ItIsNotAPlayer** [comment]
Line 42 `中文` --> `中午`
Line 103 `挂起` --> `刮起`
Line 294 `原本` --> `原版`

**Comment by ItIsNotAPlayer** [comment]
Line 42 `中文` --> `中午`
Line 103 `挂起` --> `刮起`
Line 294 `原本` --> `原版`

**Comment by sixthsurge** [comment]
sorry I forgot about this, I'm now using the Chinese translation by Nakiruri

**Pull request closed without merging**
