### PR TITLE
added reversed shadow culling

### PR DESCRIPTION
**Pull request by Candymanmax**
improves performance by 20% when coloured lights are enabled
default settings: 
default settings with coloured lights and reversed shadow culling: 
default settings with coloured lights:

### CODE REVIEW

**Comment by sixthsurge** [comment]
wow that's cool I didn't know that existed

**Comment by sixthsurge** [comment]
would it be a good idea to make voxeldistance depend on VOXEL_VOLUME_SIZE? you can't have it be based on a formula but you can use a chain of #ifs to select the right value (I'm sure there's some examples of this in photon)

**Comment by Candymanmax** [comment]
it'd probably be better as a seperate slider in my opinion. if it scaled with it then you kinda lose the main gain of enabling it in the first place.

**Comment by sixthsurge** [comment]
won't that fuck up the lighting outside of the range?

**Comment by Candymanmax** [comment]
not that I've noticed, it is doing a 3x3 chunk radius that is fully voxelized and then it's only visible stuff that gets lights from there on out so maybe a slider should be added but I'll see about adding it if I come across any issues with it

**Comment by sixthsurge** [comment]
are you sure it's only visible stuff and not only stuff that's visible to the sun? also, isn't the constant actually called voxelDistance?

**Comment by xirreal** [comment]
I'd like to note that this is an Iris only feature, documented [here](https://github.com/IrisShaders/ShaderDoc/blob/master/iris-features.md#reversed-shadow-culling-iris-166). The gist of it is basically normal shadowmap culling (based on player view frustum) + configurable square area around the player.

**Comment by Candymanmax** [comment]
yeah, I'll update the pr later today with it being linked the voxel volume and then also updating the constant name to be right.

**Comment by sixthsurge** [comment]
actually IMS also recommends to do it how you did it with only a short vowel distance
so I think I was wrong

**Comment by Candymanmax** [comment]
so I shouldn't change anything or should I still link it to the voxel volume slider?

**Comment by Candymanmax** [comment]
I've updated the pr if you wanna merge it

**Pull request closed without merging**
